server:
  port: 8090
spring:
  application:
    name: security-web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://152.136.119.254:3306/security-sample?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/