server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harper-yang/spring-security-sample.git
          search-paths: spring-config-repo/
      label: master
  application:
    name: config-server
