server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harper-yang/spring-security-sample.git
          search-paths: spring-config-repo/
      label: master
  application:
    name: config-server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/, http://${eureka.instance.hostname}:8762/eureka/, http://${eureka.instance.hostname}:8763/eureka/
