server:
  port: 6666
spring:
  rabbitmq:
    host: 152.136.119.254
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        # 对应 RabbitProperties.ListenerRetry 类
        retry:
          enabled: true # 开启消费重试机制
          max-attempts: 3 # 最大重试次数。默认为 3 。
          initial-interval: 1000 # 重试间隔，单位为毫秒。默认为 1000 。
