server:
  port: 8899
spring:
  application:
    name: security-web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://152.136.119.254:3306/security-sample?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver