#server:
#  port: 8090
#spring:
#  application:
#    name: security-web
#  datasource:
#    url: jdbc:mysql://152.136.119.254:3306/security_config?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: mysql
#    driver-class-name: com.mysql.jdbc.Driver